### ISSUE TITLE
[Suggestion] Trizen support

### ISSUE THREAD

**Issue by Henry-Hiles** [Vonr/parui#2]
I love this application, it's really great, but support for the AUR helper trizen would be amazing. Right now you can specify to use trizen, but it does error once in a while (I think because trizen has some small differences from yay or paru)

**Comment by Vonr** [comment]
I thought 1.0.0 would fix this, but apparently trizen does not support -Slq (list installable packages) which makes it even more difficult to support. Unfortunately, I don't belive this feature will be coming any time soon. Paru continues to be parui's primary target.

**Comment by Vonr** [comment]
1.0.2 should fix this when it comes out.

**Comment by Vonr** [comment]
Completed in 1.0.3.
